### ISSUE TITLE
Error compiling Cython file... not a valid module name

### ISSUE THREAD

**Issue by karl616** [uci-cbcl/tree-hmm#2]
Trying to compile the code directly out of the box as described in the readme, I got the following error:

cythoning treehmm/vb_mf.pyx to treehmm/vb_mf.c
## Error compiling Cython file:

...
# !python
## ^

treehmm/vb_mf.pyx:1:0: 'treehmm/vb_mf' is not a valid module name
building 'treehmm/vb_mf' extension
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/home/projects/src/treehmm/treeEnv/lib/python2.6/site-packages/numpy/core/include -I/usr/include/python2.6 -c treehmm/vb_mf.c -o build/temp.linux-x86_64-2.6/treehmm/vb_mf.o
treehmm/vb_mf.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
error: command 'gcc' failed with exit status 1

I used cython 19.1 ...

How to fix it:
The solution is to change module names in the setup.py file. The ext_modules variable.. treehmm/vb_mf should be treehmm.vb_mf, but only the first instance. Not the one referring the file. This goes for the remaining three instances in this array as well:

treehmm/vb_mf >> treehmm.vb_mf
treehmm/vb_prodc >> treehmm.vb_prodc
treehmm/vb_prodc_sepTheta >> treehmm.vb_prodc_sepTheta
treehmm/clique_hmm >> treehmm.clique_hmm

**Comment by jakebiesinger** [comment]
Thanks for pointing this out.  The move to a package structure was a recent change and I must have had old shared objects sitting around.

Fixed in aab0f63d929e537d131f85f16fe1c4b80df9b38f.
